Repository stolostron/multicloud-operators-channel, pull requests merged in 2019-10, with the labels that each got.

#2 initial check with CRD only
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  Makefile
  OWNERS
  README.md
  RELEASE.md
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/scripts/config_docker.sh
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  deploy/crds/app_v1alpha1_channel_cr.yaml
  deploy/crds/app_v1alpha1_channel_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  docs/development.md
  go.mod
  go.sum
  hack/boilerplate.go.txt
  pkg/apis/addtoscheme_app_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/app/group.go
  pkg/apis/app/v1alpha1/channel_types.go
  pkg/apis/app/v1alpha1/doc.go
  pkg/apis/app/v1alpha1/register.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_channel.go
  pkg/controller/channel/channel_controller.go
  pkg/controller/controller.go
  tools.go
  version/version.go
Labels: approved, lgtm, size/XXL

#4 update badge, fix Makefile and migrate type test cases
  Makefile
  README.md
  go.mod
  go.sum
  pkg/apis/app/v1alpha1/channel_types.go
  pkg/apis/app/v1alpha1/channel_types_test.go
  pkg/apis/app/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  version/version.go
Labels: approved, lgtm, size/L

#5 add badge and update opeartor-sdk version to 0.10.0
  Makefile
  README.md
  common/scripts/codecov.sh
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#6 Update channel_types.go
  .github/dco.yml
  pkg/apis/app/v1alpha1/channel_types.go
Labels: approved, lgtm, size/XS

#7 Update app_v1alpha1_channel_crd.yaml
  deploy/crds/app_v1alpha1_channel_crd.yaml
Labels: approved, lgtm, size/XS
