Repository stolostron/multicloud-operators-channel, pull requests merged in 2020-03, with the labels that each got.

#33 Update synchronizer.go
  pkg/synchronizer/githubsynchronizer/synchronizer.go
Labels: lgtm, size/M

#34 Update synchronizer.go (#33)
  pkg/synchronizer/githubsynchronizer/synchronizer.go
Labels: size/M

#36 fix deployable deletion
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/objectstore/objectstore_controller.go
  pkg/utils/deployable.go
  pkg/utils/deployable_test.go
  pkg/utils/utilconsts.go
Labels: size/M

#35 Update COMPONENT_NAME
  COMPONENT_NAME
  COMPONENT_VERSION
  build/Dockerfile
Labels: size/XS

#41 remove github token from build harness download
  .travis.yml
  Makefile
Labels: lgtm

#46 fixing gosec:G304
  go.mod
  go.sum
  pkg/synchronizer/githubsynchronizer/githubsynchronizer.go
Labels: lgtm

#49 make: add github token back to build harness download
  Makefile
Labels: lgtm

#48 testing push latest tag to quay.io
  .travis.yml
  Makefile
Labels: lgtm

#55 Izhang fix insecureskipverify
  pkg/synchronizer/helmreposynchronizer/helmreposynchronizer.go
  pkg/utils/helmrepo.go
  pkg/utils/helmrepo_test.go
Labels: lgtm

#57 watch Clusters only when the ACM Cluster API service is ready
  cmd/manager/exec/manager.go
  go.mod
  go.sum
  pkg/controller/channel/channel_controller.go
Labels: lgtm

#59 trigger travis
  README.md
Labels: lgtm

#61 Izhang coverage improve attempt 2
  go.mod
  pkg/controller/channel/channel_controller.go
  pkg/controller/channel/channel_controller_test.go
  pkg/utils/deployable.go
Labels: lgtm

#65 requeue channel when cant list clusters
  pkg/controller/channel/channel_controller.go
  pkg/controller/channel/channel_controller_test.go
Labels: lgtm

#62 Do not delete subscription type deployables
  pkg/apis/apps/v1/channel_types.go
  pkg/synchronizer/githubsynchronizer/githubsynchronizer.go
  pkg/synchronizer/helmreposynchronizer/helmreposynchronizer.go
  pkg/utils/github.go
  pkg/utils/github_test.go
  pkg/utils/utilconsts.go
Labels: lgtm

#69 fix incorrect struct initialization
  pkg/controller/channel/channel_controller.go
  pkg/utils/github.go
Labels: lgtm
