Repository stolostron/multicloud-operators-channel, pull requests merged in 2020-06, with the labels that each got.

#89 Izhang validation webhook
  cmd/manager/exec/manager.go
  deploy/standalone/clusterrole.yaml
  deploy/standalone/clusterrole_binding.yaml
  deploy/standalone/operator.yaml
  deploy/standalone/service.yaml
  deploy/standalone/service_account.yaml
  go.mod
  go.sum
  pkg/webhook/certificate.go
  pkg/webhook/certificate_test.go
  pkg/webhook/channel_validator.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_suite_test.go
  pkg/webhook/webhook_test.go
  pkg/webhook/wireupwebhook.go
Labels: approved

#90 adding security contact info
  SECURITY.md
Labels: approved, lgtm

#91 upgrade operator sdk to v0.18
  go.mod
  go.sum
  pkg/apis/apps/v1/v1_suite_test.go
  pkg/controller/channel/channel_controller_suite_test.go
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_suite_test.go
  pkg/controller/helmrepo/helmrepo_controller_suite_test.go
  pkg/controller/objectstore/objectstore_controller_suite_test.go
  pkg/synchronizer/helmreposynchronizer/synchronizer_set_up_test.go
  pkg/synchronizer/objectstoresynchronizer/synchronizer_suite_test.go
  pkg/utils/deployable_test.go
  pkg/utils/utestsetup_suite_test.go
  pkg/webhook/webhook_suite_test.go
Labels: approved

#92 fix the empty ns for reference resources
  pkg/controller/channel/channel_controller.go
  pkg/synchronizer/helmreposynchronizer/helmreposynchronizer.go
Labels: approved

#93 change webhook service selector to pod label
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/webhook/wireupwebhook.go
Labels: approved

#94 fix snoar gate
  build/run-code-lint.sh
  pkg/controller/channel/channel_controller.go
  pkg/synchronizer/objectstoresynchronizer/object_synchronizer.go
  pkg/utils/deployable.go
Labels: approved, lgtm

#95 loosen up the validation check
  pkg/webhook/channel_validator.go
  pkg/webhook/wireupwebhook.go
Labels: approved, lgtm

#96 Update Dockerfile
  build/Dockerfile
Labels: lgtm
