Repository stolostron/multicloud-operators-channel, pull requests merged in 2021-05, with the labels that each got.

#167 support for AWS S3 object bucket channel
  go.mod
  go.sum
  pkg/controller/objectstore/objectstore_controller_test.go
  pkg/synchronizer/objectstoresynchronizer/object_synchronizer.go
  pkg/utils/aws_client.go
  pkg/utils/channel.go
  pkg/utils/channel_descriptor.go
  pkg/utils/fakeObjectStore.go
  pkg/utils/helmrepo.go
Labels: approved, dco-signoff: yes

#168 Don't create channel role/rolebinding if the channel is in ACM NS
  cmd/manager/exec/manager.go
  pkg/controller/channel/channel_controller.go
  pkg/controller/channel/channel_controller_test.go
  pkg/controller/controller.go
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/helmrepo/helmrepo_controller.go
  pkg/controller/objectstore/objectstore_controller.go
Labels: approved, dco-signoff: yes, lgtm

#169 stop helmrepo and objectStore controller
  .github/workflows/kind.yml
  build/run-e2e-tests.sh
  pkg/controller/add_helmrepo.go
  pkg/controller/add_objectstore.go
Labels: approved, dco-signoff: yes, lgtm

#170 Revert "update minio e2e test object store access"
  examples/channel-alone/objectstore_channel_e2e.yaml
Labels: approved, dco-signoff: yes

#171 apply kind v0.9.0 and add back chn-003, chn-004 e2e test cases
  build/run-e2e-tests.sh
  e2e/e2e_test.go
Labels: dco-signoff: yes

#163 do not default to amd64 if GOARCH is not set
  common/scripts/gobuild.sh
Labels: approved, dco-signoff: yes, lgtm

#174 Change spec to required
  deploy/crds/apps.open-cluster-management.io_channels_crd.yaml
  pkg/apis/apps/v1/channel_types.go
Labels: approved, dco-signoff: yes, lgtm
