Repository stolostron/multicloud-operators-channel, pull requests merged in 2022-01, with the labels that each got.

#196 cve fix
  Makefile.prow
  go.mod
  go.sum
Labels: approved, dco-signoff: yes

#197 cve fix for release-2.4
  Makefile.prow
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#202 stolostron
  .gitignore
  Makefile
  README.md
  build/run-e2e-tests.sh
  build/test-package.sh
  cmd/manager/exec/manager.go
  cmd/manager/main.go
  common/config/.golangci.yml
  go.mod
  go.sum
  pkg/apis/addtoscheme_apps_v1.go
  pkg/apis/apps/v1/zz_generated.openapi.go
  pkg/controller/add_channel.go
  pkg/controller/add_deployable.go
  pkg/controller/channel/channel_controller.go
  pkg/controller/channel/channel_controller_suite_test.go
  pkg/controller/channel/channel_controller_test.go
  pkg/controller/controller.go
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_suite_test.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/helmrepo/helmrepo_controller.go
  pkg/controller/helmrepo/helmrepo_controller_suite_test.go
  pkg/controller/helmrepo/helmrepo_controller_test.go
  pkg/controller/objectstore/channel_operation.go
  pkg/controller/objectstore/objectstore_controller.go
  pkg/controller/objectstore/objectstore_controller_suite_test.go
  pkg/controller/objectstore/objectstore_controller_test.go
  pkg/synchronizer/helmreposynchronizer/helmreposynchronizer.go
  pkg/synchronizer/helmreposynchronizer/synchronizer_set_up_test.go
  pkg/synchronizer/helmreposynchronizer/synchronizer_test.go
  pkg/synchronizer/objectstoresynchronizer/object_synchronizer.go
  pkg/synchronizer/objectstoresynchronizer/synchronizer_suite_test.go
  pkg/synchronizer/objectstoresynchronizer/synchronizer_test.go
  pkg/utils/channel.go
  pkg/utils/channel_descriptor.go
  pkg/utils/channel_descriptor_test.go
  pkg/utils/channel_test.go
  pkg/utils/deployable.go
  pkg/utils/deployable_test.go
  pkg/utils/utestsetup_suite_test.go
  pkg/webhook/channel_validator.go
  pkg/webhook/channel_validator_test.go
  pkg/webhook/webhook_suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#203 stolostron
  .gitignore
  Makefile
  README.md
  build/Dockerfile.prow
  build/run-e2e-tests.sh
  build/test-package.sh
  cmd/manager/exec/manager.go
  cmd/manager/main.go
  common/config/.golangci.yml
  go.mod
  go.sum
  pkg/apis/addtoscheme_apps_v1.go
  pkg/apis/apps/v1/zz_generated.openapi.go
  pkg/controller/add_channel.go
  pkg/controller/add_deployable.go
  pkg/controller/channel/channel_controller.go
  pkg/controller/channel/channel_controller_suite_test.go
  pkg/controller/channel/channel_controller_test.go
  pkg/controller/controller.go
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_suite_test.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/helmrepo/helmrepo_controller.go
  pkg/controller/helmrepo/helmrepo_controller_suite_test.go
  pkg/controller/helmrepo/helmrepo_controller_test.go
  pkg/controller/objectstore/channel_operation.go
  pkg/controller/objectstore/objectstore_controller.go
  pkg/controller/objectstore/objectstore_controller_suite_test.go
  pkg/controller/objectstore/objectstore_controller_test.go
  pkg/synchronizer/helmreposynchronizer/helmreposynchronizer.go
  pkg/synchronizer/helmreposynchronizer/synchronizer_set_up_test.go
  pkg/synchronizer/helmreposynchronizer/synchronizer_test.go
  pkg/synchronizer/objectstoresynchronizer/object_synchronizer.go
  pkg/synchronizer/objectstoresynchronizer/synchronizer_suite_test.go
  pkg/synchronizer/objectstoresynchronizer/synchronizer_test.go
  pkg/utils/channel.go
  pkg/utils/channel_descriptor.go
  pkg/utils/channel_descriptor_test.go
  pkg/utils/channel_test.go
  pkg/utils/deployable.go
  pkg/utils/deployable_test.go
  pkg/utils/utestsetup_suite_test.go
  pkg/webhook/channel_validator.go
  pkg/webhook/channel_validator_test.go
  pkg/webhook/webhook_suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#201 stolostron
  .gitignore
  Makefile
  README.md
  build/run-e2e-tests.sh
  build/run-unit-tests.sh
  cmd/manager/exec/manager.go
  cmd/manager/main.go
  common/config/.golangci.yml
  go.mod
  go.sum
  pkg/apis/addtoscheme_apps_v1.go
  pkg/apis/apps/v1/zz_generated.openapi.go
  pkg/controller/add_channel.go
  pkg/controller/add_deployable.go
  pkg/controller/add_helmrepo.go
  pkg/controller/add_objectstore.go
  pkg/controller/channel/channel_controller.go
  pkg/controller/channel/channel_controller_suite_test.go
  pkg/controller/channel/channel_controller_test.go
  pkg/controller/controller.go
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_suite_test.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/helmrepo/helmrepo_controller.go
  pkg/controller/helmrepo/helmrepo_controller_suite_test.go
  pkg/controller/helmrepo/helmrepo_controller_test.go
  pkg/controller/objectstore/channel_operation.go
  pkg/controller/objectstore/objectstore_controller.go
  pkg/controller/objectstore/objectstore_controller_suite_test.go
  pkg/controller/objectstore/objectstore_controller_test.go
  pkg/synchronizer/helmreposynchronizer/helmreposynchronizer.go
  pkg/synchronizer/helmreposynchronizer/synchronizer_set_up_test.go
  pkg/synchronizer/helmreposynchronizer/synchronizer_test.go
  pkg/synchronizer/objectstoresynchronizer/object_synchronizer.go
  pkg/synchronizer/objectstoresynchronizer/synchronizer_suite_test.go
  pkg/synchronizer/objectstoresynchronizer/synchronizer_test.go
  pkg/utils/channel.go
  pkg/utils/channel_descriptor.go
  pkg/utils/channel_descriptor_test.go
  pkg/utils/channel_test.go
  pkg/utils/deployable.go
  pkg/utils/deployable_test.go
  pkg/utils/utestsetup_suite_test.go
  pkg/webhook/channel_validator.go
  pkg/webhook/channel_validator_test.go
  pkg/webhook/webhook_suite_test.go
Labels: lgtm, dco-signoff: yes

#204 stolostron
  build/Dockerfile.prow
Labels: approved, dco-signoff: yes

#206 Use updated e2e tests
  build/run-e2e-tests.sh
Labels: lgtm, approved, dco-signoff: yes
