Repository stolostron/multicloud-operators-channel, pull requests merged in 2022-06, with the labels that each got.

#222 trigger build
  README.md
Labels: approved, dco-signoff: yes

#223 Update component version
  COMPONENT_VERSION
Labels: approved, dco-signoff: yes

#224 Fix cve CVE-2022-31030
  build/run-e2e-tests.sh
  go.mod
  go.sum
Labels: dco-signoff: yes

#227 trigger image rebuild
  README.md
Labels: lgtm, approved, dco-signoff: yes

#228 Add apiextensions to scheme
  cmd/manager/exec/manager.go
Labels: lgtm, approved, dco-signoff: yes

#229 [release-2.5] CVE-2022-31030
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#232 Remove hardcoded user uid from dockerfile
  build/Dockerfile
  build/Dockerfile.prow
Labels: lgtm, approved, dco-signoff: yes

#233 Revert removal of user uid from dockerfile
  build/Dockerfile
  build/Dockerfile.prow
Labels: approved, dco-signoff: yes
